### ISSUE TITLE
Proxy support?

### ISSUE THREAD

**Issue by oedstero** [certificate-helper/Certificate-Inspector#25]
I'm trying to troubleshoot an issue with IOS10 and SSL through a custom PAC file..  If a proxy is defined in network settings it would be great for this app to parse and use them ...

**Comment by ecnepsnai** [comment]
Hi @oedstero, and thank you for the request!

The proxy settings on iOS is restricted to HTTP requests only, and Certificate Inspector doesn't make any HTTP requests when querying the domain. It simply establishes a TLS connection, gathers all of the servers certificate information, and disconnects. Therefor the connection would not go through the proxy.

I'll investigate the possibility of specifying proxy settings somehow within the application.

**Comment by oedstero** [comment]
Thanks ..  for what it's worth, we have had success up until recently using stanzas like this in a PAC file : 
```
    if ( url.match(/^https:/) ) {
      return 'PROXY myproxy.mydomain.com:8080';
    }
```
where :8080 hosts a remapping proxy which maps CONNECTs to their respective hosts in development and staging environments.  Looks like the latest IOS10 builds may force us to cease doing this.

**Comment by ecnepsnai** [comment]
With ATS, you should be able to specify that specific domain and permit HTTP requests on it in your applications info file.

Apple is planning to cut back on developers who simply turned off ATS and left it off, with no valid reason.

Apple may require justification as to why you're disabling ATS for the domain, but you should be fine without needing to disable ATS entirely.

However this is beyond the scope of Certificate Inspector, so I'm closing this issue.
